"""The DrawingEngine port. Anything that can create a canvas, draw shapes/text/paths,
apply a gradient, paint with a brush, and export a PNG can implement this and be
swapped in behind the MCP tool layer. GIMP is one adapter, not a dependency of the domain.
"""
from typing import Protocol
from .types import BrushHandle, BrushSpec, CanvasHandle, Color, GradientStyle, LayerHandle, PathSegment


class DrawingEngine(Protocol):
    def create_canvas(self, width: int, height: int, bg: Color) -> CanvasHandle: ...
    def close(self, canvas: CanvasHandle) -> None: ...
    def new_layer(self, canvas: CanvasHandle, name: str) -> LayerHandle: ...
    def draw_ellipse(self, canvas: CanvasHandle, cx: float, cy: float, rx: float, ry: float, fill: Color, layer: LayerHandle | None = None) -> None: ...
    def draw_rect(self, canvas: CanvasHandle, x: float, y: float, w: float, h: float, fill: Color, layer: LayerHandle | None = None) -> None: ...
    def draw_path(self, canvas: CanvasHandle, segments: list[PathSegment], stroke_color: Color | None, stroke_width: float, fill_color: Color | None, layer: LayerHandle | None = None) -> None: ...
    def draw_gradient(self, canvas: CanvasHandle, fg: Color, bg: Color, style: GradientStyle = "linear", layer: LayerHandle | None = None) -> None: ...
    def add_text(self, canvas: CanvasHandle, text: str, x: float, y: float, size: float, color: Color, font: str | None = None, layer: LayerHandle | None = None) -> None: ...
    def list_brushes(self, canvas: CanvasHandle) -> list[str]: ...
    def register_brush(self, canvas: CanvasHandle, spec: BrushSpec) -> BrushHandle: ...
    def release_brush(self, canvas: CanvasHandle, brush: BrushHandle) -> None: ...
    def paint_stroke(self, canvas: CanvasHandle, brush: BrushHandle, segments: list[PathSegment], color: Color, layer: LayerHandle | None = None) -> None: ...
    def paint_dab(self, canvas: CanvasHandle, brush: BrushHandle, x: float, y: float, color: Color, size: float | None = None) -> None: ...
    def export(self, canvas: CanvasHandle, filename: str) -> int: ...
